version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./:/app
      - bot_data:/app/data
    environment:
      - TZ=Europe/Moscow
      # Настройки для Google Sheets
      - USE_GOOGLE_SHEETS=True
      - GOOGLE_SHEET_NAME=Post24man_Data
      # Другие переменные окружения загружаются из .env файла
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot_network

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - TZ=Europe/Moscow
      - N8N_ENCRYPTION_KEY=change_me_for_production
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:

volumes:
  bot_data:
  n8n_data: 